### ISSUE TITLE
JSON stream parser

### ISSUE THREAD

**Issue by dbalabka** [amphp/parser#1]
I would like to propose to implement JSON stream parsing. I assume that it can be beneficial in case of REST APIs response/requests parsing to map JSON directly into predifined class objects to avoid intermediate array or stdClass representation. Especialy for libraries that provides integration with 3rd-party API.

As a example I can reference to [Jackson Streaming API](http://www.baeldung.com/jackson-streaming-api).

Also there are multiple PHP libraries that provides JSON stream parse:
- https://github.com/salsify/jsonstreamingparser
- https://github.com/WyriHaximus/reactphp-stream-json

and encoding:
- https://github.com/violet-php/streaming-json-encoder

or both:
- https://github.com/skolodyazhnyy/json-stream

**Comment by kelunik** [comment]
Having an intermediate state and mapping that to an object will probably be way faster than a custom userland implementation of a JSON parser.

A streaming JSON parser (streaming one JSON object, not line-delimited JSON) is only really worth it if you have really large payloads that can be processed order-independent. Otherwise there's not much benefit, because the complexity increases and the performance degrades (because userland PHP).

**Comment by kelunik** [comment]
I'm going to close this one. If you want a streaming parser, use one of the options provided above. If you're looking for line-delimited JSON, use https://github.com/kelunik/streaming-json.
